version: '3.4'

services:
  jtabackend:
    image: jtabackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080:8080
      - 5005:5005

  jobtrackerfrontend:
    image: jobtrackerfrontend
    build:
      context: job-tracker-frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
